############################################
#
# Possible values for server_conf role
# 
# Follows Splunk server.conf.spec closely
#
############################################

splunk_server_conf:
  general:
    pass4Symmkey: <password>
    * Encrypted password

    site: [dynamic|<site>]
    * The site where the system is located. Dynamic will use site attribute from inventory

    trustedIP: <IP address>
    * Trusted IP for SSO

  sslConfig:
    sslKeysfilePassword: <password>
    * Encrypted password 

  license:
    master_uri: [dynamic|<uri>]
    * Dynamic will use inventory to detect

  clustering:
    mode: [master|slave|searchhead|disabled]
    * Defaults to disabled

    master_uri: [<uri> | clustermaster:stanzaName1, clustermaster:stanzaName2]
    * URI of the cluster master that this slave or searchhead should connect to.
    
    pass4SymmKey: <password>
    * Encrypted password
 
    multisite: [true|false]
    * Defaults to false

    replication_factor: <positive integer>
    * Defaults to 3

    site_replication_factor: <comma-separated string>
    * Defaults to "origin:2,total:3"
    * Note: no spaces allowed between comma separated values

    search_factor:  <positive integer>
    * Defaults to 2

    available_sites:
      - [site1]
      - [site2]
     * List of available sites
     * Defaults to an empty string. So if multisite is turned on this needs to be explicitly set

     cluster_label: [dynamic|<string>]
     * Defaults to an empty string.
     * Use dynamic to set automatically

  replication_port:
    port: <port>
    * Replication port

  replication_port_ssl:
    port: <port>

    rootCA: <filepath>
    * Certificate authority list
    * Autogenerated file under $SPLUNK_HOME/etc/auth/cacert.pem

    serverCert: <filepath>
    * Full path to the server certificate.
    * Autogenerated file under $SPLUNK_HOME/etc/auth/server.pem

    password: <string>
    * Encrypted password


